<a href="https://colab.research.google.com/github/nikhilv2/Machine-Learning/blob/main/Simple_Neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([[0,1,0],[0,1,1],[1,0,0],[1,0,1]])
y = np.array([[0],[0],[1],[1]])

In [ ]:
x

array([[0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])

In [ ]:
y

array([[0],
       [0],
       [1],
       [1]])

In [ ]:
##Assign the weight (random)
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [ ]:
sum = np.dot(x,weights) +.02
sum

array([[0.04075195],
       [0.67440018],
       [0.79132064],
       [1.42496888]])

In [ ]:
def activation(x):
  return 1/(1+np.exp(-x))               ##sigmoid

In [ ]:
ypred = activation(sum)
ypred

array([[0.51018658],
       [0.66248773],
       [0.68811483],
       [0.8061162 ]])

In [ ]:
ypred.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
def gradient(a,x):
  return a*x*(1-x)

In [ ]:
sum = np.dot(x,weights) +.02
ypred = activation(sum)
error = y-ypred
error

array([[-0.51018658],
       [-0.66248773],
       [ 0.31188517],
       [ 0.1938838 ]])

In [ ]:
sum = np.dot(x,weights) +.02
ypred = activation(sum)
error = y- ypred
weight_change = gradient(error,ypred)  #Gradient descent
weights = weights+ np.dot(x.T,weight_change)                              
error                                 ## when we run again and again, the error will gradually reduce. so train the text in a loop

array([[-0.38144441],
       [-0.48099052],
       [ 0.27290608],
       [ 0.1998431 ]])

In [ ]:
for i in range(500):                         ### Training the model for 500 times to reduce the error
  sum = np.dot(x,weights) +.02 
  ypred = activation(sum)
  error = y- ypred
  weight_change = gradient(error,ypred)  #Gradient descent
  weights = weights+ np.dot(x.T,weight_change)  
error

array([[-0.02318573],
       [-0.02334888],
       [ 0.02341204],
       [ 0.02324847]])

In [ ]:
ypred                            ## The required values are [0,0,1,1]  

array([[0.02318573],
       [0.02334888],
       [0.97658796],
       [0.97675153]])

In [ ]:
ypred.round()              ##Rounding off

array([[0.],
       [0.],
       [1.],
       [1.]])

In [ ]:
weights

array([[ 3.71187748],
       [-3.76181695],
       [ 0.00717439]])